global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: actorlib_example_fab
    static_configs:
      - targets: ["192.168.199.167:8089"]
  - job_name: rssant_worker
    static_configs:
      - targets: ["192.168.199.167:6795"]
  - job_name: rssant_harbor
    static_configs:
      - targets: ["192.168.199.167:6793"]
  - job_name: rssant_scheduler
    static_configs:
      - targets: ["192.168.199.167:6791"]
